version: '2'

services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/amplatform
  production:
    image: ${DOCKER_USER_ID}/amplatform:${BUILD_NUMBER}
    container_name: amplatform
    ports:
      - '8081:8081'
    environment:
      - "SPRING_PROFILES_ACTIVE=prd"
